### ISSUE TITLE
Task chaining failure due to mismatched task-type and then-overload.

### ISSUE THREAD

**Issue by inamiy** [ReactKit/SwiftTask#37]
As discussed in https://gist.github.com/tokorom/19ae87acf9db5386c0e1 by @tokorom,

```
self.request1()
    .success { _ -> Task<Progress, Int, Bool> in
        // A
        return self.request2()
    }
    .success { _ in
        // B
    }
```

(B) gets called first before `self.request2()` completes.
This occurs when `func request1()` and `func request2()` returns Task type with different Error type,
so that type-inference will fail and uses "map" version of `then` rather than "flatMap" version of it.

We need more strict type constraint to avoid this issue, or add an alias method name to distinguish two methods.

**Comment by tokorom** [comment]
@inamiy Thank you for fixing this problem.

I could confirm that the task chaining with multi error types to succeed in my project :+1:
