### ISSUE TITLE
Swift 2.0 support?

### ISSUE THREAD

**Issue by katopz** [ReactKit/SwiftTask#40]
Plenty of breaking there. Anyone working on this?

**Comment by inamiy** [comment]
I started working on `swift/2.0` branch.
Current 52b976d will work fine, but I'm planning to refactor some codes in future.

**Comment by katopz** [comment]
@inamiy Many thanks! :D

**Comment by dtissera** [comment]
Hello,

Can you commit a tag for swift 2.0 support ? I use your library in a pod and I is not possible to add a dependency on a pod on a specific branch.
http://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of

Thanks with friendly

**Comment by inamiy** [comment]
Sorry for being late.
I just published ver 4.0.0 (4cfb920) for CocoaPods as well.
Please take a try :)
