### ISSUE TITLE
Canceling/aborting a task that is running with task.try()

### ISSUE THREAD

**Issue by sahandnayebaziz** [ReactKit/SwiftTask#47]
I'm sorry for asking in potentially the wrong place, but I haven't been able to completely cancel a task that I started with task.try().

I have tasks that belong to table view cells, and so I'm looking for the way to cancel/abort a task that is running on a cell that is about to scroll off of the screen and therefore no longer needs to be running (as it is now in the background).

Is there a way to cancel/abort/kill a task?

**Comment by inamiy** [comment]
I think `let retryableTask = someTask.try(n); retryableTask.cancel()` will work as I wrote its test previously in [SwiftTaskTests.swift#L955-L1015](https://github.com/ReactKit/SwiftTask/blob/1e7b2850c742b237ad0f207a6e471d2a0db1fd97/SwiftTaskTests/SwiftTaskTests.swift#L955-L1015).

Please check followings:
- Check `retryableTask.state`: your `retryableTask` should still be `.Running` or `.Paused` before calling `retryableTask.cancel()`
- Make sure you are cancelling `retryableTask`, not `someTask`
- Check concurrency where execution might be blocking the call of `cancel()`

**Comment by inamiy** [comment]
I think above mentioned will solve this issue, so I will close for now.

Also, please note that `try(n)` is now renamed to `retry(n-1)` in d127eed, for ver 4.0.0 (4cfb920).
