### ISSUE TITLE
Run closure of promise/future on main ui thread

### ISSUE THREAD

**Issue by iliraga** [ReactKit/SwiftTask#48]
Is it possible to run the Promise-Closure on the main thread? Sometimes I want to perform a UI asynchronous operation like requesting permissions to user etc. If those are runned in separate threads, they are not shown to the user... I wasn't able to found any solution in documentation or sourcecode

**Comment by inamiy** [comment]
You can use any threading techniques e.g. Grand Central Dispatch inside `Task` initialization
to deliver fulfill/reject events on your target thread/queue.

Please see below as an example:
https://github.com/ReactKit/SwiftTask/blob/16c08c095d63af4c8595d7057209e4318d19cacb/Playgrounds/02-Async.playground/Contents.swift#L25-L33
