### ISSUE TITLE
Cancel task from initClosure

### ISSUE THREAD

**Issue by Koshub** [ReactKit/SwiftTask#62]
Not sure is it clear how to cancel task from its initClosure block. I can manage progress, configure, reject or fullfill but it is absent or not so clear described in documentation how to cancel it. For example:

``` swift
let task = Task<Float, Int, ErrorType>(paused: true) { (progress, fulfill, reject, configure) in
    progress.cancel() // should be something like this ?
}
```

**Comment by inamiy** [comment]
Cancellation is intended to be applied only from outer scope of `Task`'s initialization closure. Inside that, you can only call `reject` with sending some error.

**Comment by Koshub** [comment]
I see. It is better to use one-way control flow.
